### ISSUE TITLE
Reporte de Práctica #2

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-IsaHuerta23#2]
Reporte de Práctica - Práctica en DLL en C en Visual Studio 

[Reporte de Práctica #2.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-IsaHuerta23/files/6339396/Reporte.de.Practica.2.pdf)

**Comment by DuilioAquino10** [comment]
Calificacion 20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
